INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (1, 'Sleep', 1, 'General');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (2, 'Stress', 2, 'General');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (3, 'Interest in Activities', 3, 'General');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (4, 'Concentration', 4, 'General');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (5, 'Irritability', 5, 'General');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (6, 'Eating habits', 8, 'General');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (7, 'Body', 6, 'General');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (8, 'Performance', 7, 'General');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (9, 'Confidence', 1, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (10, 'Sexual Behavior', 2, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (11, 'Alcohol Use', 3, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (12, 'Recreational Drug Use', 4, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (13, 'Missed Commitments', 5, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (14, 'Hygiene', 6, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (15, 'Risky Behaviors', 7, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (16, 'Disordered Eating', 8, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (17, 'Training', 9, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (18, 'Self-harm', 10, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (19, 'Mood Swings', 11, 'Optional');
INSERT INTO balanceposition.data_point (id, name, jhi_order, jhi_type) VALUES (20, 'Meds/Supplements', 12, 'Optional');