version: 2
jobs:
  build:
    docker:
      - image: jhipster/jhipster:latest

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # run tests!
      - run: ./gradlew bootRepackage

